---
title: "R Notebook"
#output: html_notebook
---

# retreiving packages
```{r}
library(data.table)
library(ggplot2)
```
#importing data
```{r}
results <- fread("C:/Users/abusa/Documents/GitHub/ADC_Final/simulation_results.csv") #distributed noise
results_awgn <- fread("C:/Users/abusa/Documents/GitHub/ADC_Final/simulation_results_awgn.csv") #AWGN 
```


#subsetting data
```{r}
results$noise_percentage <- results$noise_length/ results$length_signal
results$error_percentage <- results$avg_hamming_distance/ results$length_signal
results_300 <- subset(results, length_signal == 300)
results_54 <- subset(results, constraint_length == '[5, 4]')
results_100noise <- subset(results, noise_percentage == 1.00)

results_awgn$error_percentage <- results_awgn$avg_hamming_distance/ results_awgn$length_signal
```




#Graphs

### Hamming Distance vs Length, Distributed Noise

```{r}
ggplot(results_100noise, aes(x = as.factor(length_signal), y = avg_hamming_distance, color = as.factor(constraint_length))) +
    geom_point(size = 2) +  labs(
        title = "Average Hamming Distance vs Signal Length for 100% of bits exposed to noise",
        x = "Signal Length (# of bits)",
        y = "Average Hamming Distance of 100 samples"
        
         ) +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))  + scale_color_discrete("[Constraint length, # of parity bits]", labels=c('[3,2]','[3,4]', '[5,2]', '[5,4]'))
```



### Hamming Distance vs Percentage of Noise, Distributed Noise

```{r}
results_300$rounded_noise <-  format(round(results_300$noise_percentage, 2), nsmall = 2)
ggplot(results_300, aes(x = as.factor(rounded_noise), y = avg_hamming_distance, color = as.factor(constraint_length))) +
    geom_point(size = 3) +  labs(
        title = "Average Hamming Distance vs Percent Noise for signal length = 300 bits",
        x = "Percentage of Bits Exposed to Noise",
        y = "Average Hamming Distance of 1000 samples"
        
         ) +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))  + scale_color_discrete("[Constraint length, # of parity bits]", labels=c('[3,2]','[3,4]', '[5,2]', '[5,4]'))
```
### Percent Error vs Length, Distributed Noise

```{r}
ggplot(results_100noise, aes(x = as.factor(length_signal), y = error_percentage, color = as.factor(constraint_length))) +
    geom_point(size = 2) +  labs(
        title = "Percent Error vs Signal Length for 100% of bits exposed to noise",
        x = "Signal Length (# of bits)",
        y = "% Error (avg hamming distance / length of signal)"
        
         ) +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))  + scale_color_discrete("[Constraint length, # of parity bits]", labels=c('[3,2]','[3,4]', '[5,2]', '[5,4]'))
```

### Hamming Distance vs Length, AWGN 

```{r}

ggplot(results_awgn, aes(x = as.factor(length_signal), y = avg_hamming_distance, color = as.factor(constraint_length))) +
    geom_point(size = 3) +  labs(
        title = "Average Hamming Distance vs Signal Length for AWGN signal",
        x = "Signal Length (# of bits)",
        y = "Average Hamming Distance of 100 samples"
        
         ) +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))  + scale_color_discrete("[Constraint length, # of parity bits]", labels=c('[3,2]','[3,4]', '[5,2]', '[5,4]'))
```

### Percent Error vs Length, AWGN 

```{r}

ggplot(results_awgn, aes(x = as.factor(length_signal), y = error_percentage, color = as.factor(constraint_length))) +
    geom_point(size = 3) +  labs(
        title = "Percent Error vs Signal Length for AWGN signal",
        x = "Signal Length (# of bits)",
        y = "% Error (avg hamming distance / length of signal)"
        
         ) +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))  + scale_color_discrete("[Constraint length, # of parity bits]", labels=c('[3,2]','[3,4]', '[5,2]', '[5,4]'))
```

